[build]
  functions = "api"
  publish = "public"

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/m3u8-fetch"
  to = "/.netlify/functions/m3u8-fetch"
  status = 200
  force = true
